-- AlterTable
ALTER TABLE "Settings" ADD COLUMN     "listItemFrom" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "listItemTo" DOUBLE PRECISION NOT NULL DEFAULT 10000,
ADD COLUMN     "noOfItemsRoListAtATime" INTEGER NOT NULL DEFAULT 100;
