export const sources = [
  { value: "buff163", label: "buff163" },
  { value: "buff_rmb", label: "buff_rmb" },
  { value: "buff_buyrmb", label: "buff_buyrmb" },
  { value: "buff_avg7", label: "buff_avg7" },
  { value: "buff_avg30", label: "buff_avg30" },
  { value: "buff_buy_avg7", label: "buff_buy_avg7" },
  { value: "buff_buy_avg30", label: "buff_buy_avg30" },
  { value: "buff_buy", label: "buff_buy" },
  { value: "csgoempire", label: "csgoempire" },
  { value: "csgoempire_avg7", label: "csgoempire_avg7" },
  { value: "csgoempire_avg30", label: "csgoempire_avg30" },
  { value: "csgoempire_coins", label: "csgoempire_coins" },
  {
    value: "csgoempire_lastsale",
    label: "csgoempire_lastsale",
  },
  { value: "waxpeer", label: "waxpeer" },
  { value: "tradeit", label: "tradeit" },
  { value: "lootfarm", label: "lootfarm" },
  { value: "bitskins", label: "bitskins" },
  {
    value: "bitskins_lastsale",
    label: "bitskins_lastsale",
  },
  { value: "steam", label: "steam" },
  { value: "steam_buy", label: "steam_buy" },
  { value: "csmoney", label: "csmoney" },
  { value: "csmoney_instant", label: "csmoney_instant" },
  { value: "csmoney_balance", label: "csmoney_balance" },
  { value: "csmoney_deposit", label: "csmoney_deposit" },
  { value: "csgoexo", label: "csgoexo" },
  { value: "csgoexo_deposit", label: "csgoexo_deposit" },
  { value: "skinport", label: "skinport" },
  { value: "swapgg", label: "swapgg" },
  { value: "swapgg_deposit", label: "swapgg_deposit" },
  { value: "dmarket", label: "dmarket" },
  { value: "dmarket_buy", label: "dmarket_buy" },
  { value: "gamdom", label: "gamdom" },
  { value: "csdeals", label: "csdeals" },
  { value: "csdeals_deposit", label: "csdeals_deposit" },
  { value: "csgofloat", label: "csgofloat" },
  { value: "shadowpay", label: "shadowpay" },
  { value: "skinbaron", label: "skinbaron" },
  { value: "vmarket", label: "vmarket" },
  { value: "itemherald", label: "itemherald" },
  { value: "swapmarket", label: "swapmarket" },
  { value: "csgoroll", label: "csgoroll" },
  { value: "skinwallet", label: "skinwallet" },
  { value: "buffmarket", label: "buffmarket" },
  { value: "buffmarket_buy", label: "buffmarket_buy" },
  { value: "csgotm", label: "csgotm" },
  { value: "csgotm_buy", label: "csgotm_buy" },
  { value: "skintrade", label: "skintrade" },
  { value: "lootbear", label: "lootbear" },
  { value: "cstrade", label: "cstrade" },
  { value: "cstrade_deposit", label: "cstrade_deposit" },
  { value: "cstrade_instant", label: "cstrade_instant" },
  { value: "gamerpay", label: "gamerpay" },
  { value: "skinthunder", label: "skinthunder" },
  { value: "lisskins", label: "lisskins" },
  { value: "lisskins_instant", label: "lisskins_instant" },
  { value: "skinsmonkey", label: "skinsmonkey" },
  {
    value: "skinsmonkey_deposit",
    label: "skinsmonkey_deposit",
  },
  { value: "whitemarket", label: "whitemarket" },
  { value: "csmoneym", label: "csmoneym" },
  { value: "skinswap", label: "skinswap" },
  { value: "nerf", label: "nerf" },
  { value: "crypto", label: "crypto" },
  { value: "c5game", label: "c5game" },
  { value: "c5game_rmb", label: "c5game_rmb" },
  { value: "cheapest", label: "cheapest" },
  { value: "skinbid", label: "skinbid" },
  { value: "youpin", label: "youpin" },
  { value: "youpin_rmb", label: "youpin_rmb" },
  { value: "mannco", label: "mannco" },
];
